version: '3'

services:
  postgres:
    image: postgres:14.8
    container_name: audi_postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

volumes:
  postgres_data: